<?php

$_lang['elementarchive'] = 'Element Archive';
$_lang['elementarchive_archivefiles'] = 'Archive Files';
$_lang['elementarchive_clear'] = 'Clear';
$_lang['elementarchive_close'] = 'Close';
$_lang['elementarchive_col1'] = 'Archive Folder';
$_lang['elementarchive_col1_qtip'] = 'Right-click Folder Name for option(s)';
$_lang['elementarchive_col2'] = 'Date/Time Created';
$_lang['elementarchive_create_msg'] = 'Creating files, please wait...';
$_lang['elementarchive_desc'] = 'Create archive files for all elements';
$_lang['elementarchive_eafiles'] = 'Archived files - Select a folder/file to view';
$_lang['elementarchive_element'] = 'Archive Folder Name';
$_lang['elementarchive_element_help'] = 'Enter the name of the folder for this archive e.g. Pre Upgrade to V2';
$_lang['elementarchive_err_dir_nf1'] = 'Archive folder';
$_lang['elementarchive_err_dir_nf2'] = 'does not exist!';
$_lang['elementarchive_err_file_nf'] = 'The file does not exist!';
$_lang['elementarchive_err_file_ns'] = 'File is not specified!';
$_lang['elementarchive_err_files_nf'] = 'Did not find any files!';
$_lang['elementarchive_err_invalid_folder'] = 'Invalid folder';
$_lang['elementarchive_err_nogo'] = 'Operation not allowed.';
$_lang['elementarchive_err_no_folder'] = 'Please enter a valid folder name!';
$_lang['elementarchive_err_path_nf'] = 'The path is not found!';
$_lang['elementarchive_err_title'] = 'Error';
$_lang['elementarchive_exit'] = 'Back';
$_lang['elementarchive_progress_text'] = 'Saving...';
$_lang['elementarchive_readme_text'] = 'This folder is used to store archives generated by ElementArchive';
$_lang['elementarchive_result'] = 'Achived Elements';
$_lang['elementarchive_remove_folder'] = 'Remove';
$_lang['elementarchive_tab'] = 'Archive Elements';
$_lang['elementarchive_view'] = 'View files';
$_lang['elementarchive_viewfile'] = 'Archived File Name';
$_lang['elementarchive_viewpanel_title'] = 'Archived Elements - File Viewer';
$_lang['elementarchive_viewtree_qtip'] = 'Click to view the contents of this file';

$_lang['setting_elementarchive_path'] = 'Element Archive Path';
$_lang['setting_elementarchive_path_desc'] = 'Enter the path where to store the Element Archive. Please ensure that the permissions are correct for manager users.';

